# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be3aa5a2139be9880f9289d42a9b56b0265aa9c68bf3505117f99c8b6f13cb90108c187c244984c3fd902f38beceefa8cd5f672a4d5dfab5475b670cc961f143

test:
  secret_key_base: 951ae5c3f7336de499845d7b864bb31d5cb7c98176ed5ca9ef89819cfe3296264e668ff68ca7f8b853ad30aa6ba2f34837bd761fe454cce07367d77086876661

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
